export const current = [
  { given: "Ana Sofia", family: "Aniceto" },
  // 2019 Akvaplan https://doi.org/10.3997/1365-2397.2018010
  // 2019 Akvaplan https://doi.org/10.1016/j.marpolbul.2019.01.009

  { given: "Marina Vàzquez", family: "Alonso", id: "mva" },
  { given: "Hector", family: "Andrade", id: "har" },
  { given: "Maj", family: "Arnberg", id: "mar" },
  { given: "Aline", family: "Arriola", id: "aar" },
  //{ given: "Starrlight", family: "Augustine", id: "sta" },
  { given: "Magnus", family: "Aune", id: "maa" },
  { given: "Gjermund", family: "Bahr", id: "gba" },
  { given: "Carl", family: "Ballantine", id: "cab" },
  { given: "Alexei", family: "Bambulyak", id: "anb" },
  { given: "Inger Margrethe", family: "Berger", id: "imb" },

  { given: "Pierre", family: "Blévin", id: "pbl" },
  { given: "Janne", family: "Blomli Johnsen", id: "jbj" },
  { given: "Katrin", family: "Bluhm", id: "kpb" },
  { given: "Trude", family: "Borch", id: "tbo" },
  { given: "Ilka", family: "Bottolfsen", id: "ibo" },
  { given: "Patti", family: "Bruns", id: "pbr" },
  { given: "Bjørn Erik", family: "Bye", id: "beb" },
  { given: "Eli", family: "Børve", id: "elb" },
  { given: "Lionel", family: "Camus", id: "lca" },
  {
    given: "JoLynn",
    family: "Carroll",
    id: "jlc",
    orcid: "0000-0002-6598-0818",
  },
  {
    given: "Michael L.",
    family: "Carroll",
    id: "mlc",
    orcid: "0000-0002-1530-6016",
  },
  { given: "Guttorm", family: "Christensen", id: "gnc" },
  { given: "Sabine", family: "Cochrane", id: "skc" },
  { given: "Geir", family: "Dahl-Hansen", id: "gdh" },
  { given: "Ida", family: "Dahl-Hansen", id: "idh" },
  { given: "Salve", family: "Dahle", id: "sda" },
  { given: "Sushmit", family: "Dhar", id: "sud" },
  { given: "Hans Kristian", family: "Djuve", id: "hkd" },
  { given: "Magnus", family: "Drivdal", id: "mad" },
  { given: "Muriel Barbara", family: "Dunn", id: "mbd" },
  { given: "Heidi", family: "Emaus", id: "hem" },
  { given: "Per-Arne", family: "Emaus", id: "pae" },
  { given: "Chris", family: "Emblow", id: "cse" },
  { given: "Anita", family: "Enok", id: "aen" },
  { given: "Steinar Dalheim", family: "Eriksen", id: "sde" },
  { given: "Håvard", family: "Espenes", id: "hes" },
  { given: "Anita", family: "Evenset", id: "aev" },
  {
    given: "Stig",
    family: "Falk-Petersen",
    id: "sfp",
    mynewsdeskID: 66553,
    icon:
      "https://resources.mynewsdesk.com/image/upload/t_article_v2/tztmgtsabezjuuqhtbli.jpg",
  },
  { given: "Reinhold", family: "Fieler", id: "ref" },
  { given: "Atle", family: "Foss", id: "atf" },
  { given: "Marianne", family: "Frantzen", id: "mfr" },
  { given: "Rosalyn", family: "Fredriksen", id: "rfr" },
  { given: "Anu", family: "Fredrikson", id: "afe" },
  { given: "Peygham", family: "Ghaffari", id: "pgh" },
  { given: "Anton", family: "Giæver", id: "agi" },
  { given: "Asle", family: "Guneriussen", id: "aig" },
  { given: "Snorri", family: "Gunnarsson", id: "sgu" },
  { given: "Arnthor", family: "Gustavsson", id: "agu" },
  { given: "Frank", family: "Gaardsted", id: "fga" },
  { given: "Claudia", family: "Halsband", id: "clh" },
  { given: "David", family: "Hammenstig", id: "dah" },
  { given: "Thor Arne", family: "Hangstad", id: "tah" },
  { given: "Jesper", family: "Hansen", id: "jha" },
  { given: "Thomas", family: "Hansen", id: "thh" },
  { given: "Astrid", family: "Harendza", id: "ahz" },
  { given: "Conrad", family: "Helgeland", id: "che" },
  { given: "Ann-Cecilie", family: "Henriksen", id: "ach" },
  { given: "Stine", family: "Hermansen", id: "she" },
  { given: "Eirik Darell", family: "Holand", id: "edh" },
  { given: "Vegard", family: "Holen", id: "vho" },
  { given: "Albert", family: "Imsland", id: "aki" },
  { given: "Kirsti", family: "Isaksen", id: "kis" },
  { given: "Trond", family: "Ivarjord", id: "tri" },
  { given: "Jenny", family: "Jensen", id: "jen" },
  { given: "Kai Arne", family: "Jenssen", id: "kaj" },
  { given: "Thor Magne", family: "Jonassen", id: "tmj" },
  { given: "Ólöf Dóra Bartels", family: "Jónsdóttir", id: "odj" },
  { given: "Lauri", family: "Kapari", id: "lka" },
  { given: "Merete", family: "Kristiansen", id: "mkr" },
  { given: "William", family: "Kristiansen", id: "wkr" },
  { given: "Ola", family: "Kvaal Brandshaug", id: "okb" },
  { given: "Jos", family: "Kögeler", id: "jwk" },
  { given: "Lars-Henrik", family: "Larsen", id: "lhl" },
  { given: "Sondre Veberg", family: "Larsen", id: "svl" },
  { given: "Bernhard", family: "Laxdal", id: "bla" },
  { given: "Øyvind", family: "Leikvin", id: "oyl" },
  { given: "Eva", family: "Leu", id: "eva" },
  { given: "Evgenija", family: "Lorentzen", id: "elo" },
  { given: "Gyda Wuttudal", family: "Lorås", id: "gwl" },
  { given: "Hans Petter", family: "Mannvik", id: "hpm" },
  { given: "Sanna", family: "Matsson", id: "sma" },
  { given: "Benjamin", family: "Merkel", id: "bme" },
  { given: "Petter", family: "Mikelborg Larsen", id: "pml" },
  { given: "Larry Ibrahim", family: "Mohammed", id: "lim" },
  { given: "Armand Moe", family: "Nes", id: "amn" },
  { given: "Jonny", family: "Nikolaisen", id: "jon" },
  { given: "Mari", family: "Nilsen", id: "mni" },
  { given: "Ane Vigdisdatter", family: "Nytro", id: "avn" },

  { given: "Jocelyn", family: "Palerud", id: "jhp" },
  { given: "Rune", family: "Palerud", id: "rpa" },
  { given: "Alexey", family: "Pavlov", id: "apa" },
  { given: "Kristine Bondo", family: "Pedersen", id: "kbo" },
  { given: "Charlotte", family: "Pedersen Ugelstad", id: "chp" },
  { given: "Ragnhild", family: "Pettersen", id: "rap" },
  { given: "Virginie", family: "Ramasco", id: "vra" },
  { given: "Achim", family: "Randelhoff", id: "rap" },
  { given: "Rune", family: "Rautio", id: "rur" },
  { given: "Gro Harlaug", family: "Refseth", id: "ghr" },
  { given: "Mette", family: "Remen", id: "mre" },
  { given: "Vera", family: "Remen", id: "vre" },
  {
    given: "Paul E.",
    family: "Renaud",
    id: "per",
    mynewsdeskID: 55035,
    icon:
      "https://resources.mynewsdesk.com/image/upload/t_article_v2/gxodjib5zt3xswf3tkog.jpg",
  },
  { given: "Kjetil", family: "Sagerup", id: "ksa" },
  { given: "Vladimir", family: "Savinov", id: "vsa" },
  { given: "Julia", family: "Seljeseth", id: "jse" },
  { given: "Andrej", family: "Sikorski", id: "avs" },
  { given: "Lars", family: "Sjetne", id: "lbs" },
  { given: "Geir Morten", family: "Skeie", id: "gms" },
  { given: "Tormod Henry", family: "Skålsvik", id: "tos" },
  { given: "Lars Olav", family: "Sparboe", id: "los" },
  { given: "Kristine Hopland", family: "Sperre", id: "khs" },
  { given: "Rikke", family: "Stabell", id: "rst" },
  { given: "Merete", family: "Stefanussen", id: "mst" },
  { given: "Kristine", family: "Steffensen", id: "krs" },
  { given: "Cathrine", family: "Stephansen", id: "cst" },
  { given: "Rune", family: "Svendsen", id: "rus" },
  { given: "Yngve", family: "Svensby", id: "yns" },
  { given: "Eva", family: "Synvis", id: "esy" },
  { given: "Emilia", family: "Sztybor", id: "esz" },
  { given: "Kamila", family: "Sztybor", id: "ksz" },
  { given: "Kristin", family: "Sæther", id: "kst" },
  { given: "Tom", family: "Sørnes", id: "tom" },
  { given: "Luca", family: "Tassara", id: "lut" },
  { given: "Morten", family: "Thorstensen", id: "mth" },
  { given: "Lisa", family: "Toske", id: "lit" },
  { given: "Roger", family: "Velvin", id: "rve" },
  { given: "Anna Andreevna", family: "Vikhrova", id: "aav" },
  { given: "Terese", family: "Vollstad-Giæver", id: "tvg" },
  { given: "Ingar", family: "Wasbotten", id: "ihw" },
  { given: "Ellie Jane", family: "Watts", id: "ejw" },
  { given: "Charlotte Teresa", family: "Weber", id: "ctw" },
  { given: "Patrick", family: "White", id: "paw" },
  { given: "Oda Sofie Bye", family: "Wilhelmsen", id: "obw" },
  { given: "Bård Harald", family: "Worum", id: "bhw" },
  { given: "Qin", family: "Zhou", id: "qin" },
  { given: "Tarald", family: "Øvrebo", id: "tko" },
  { given: "Anne Tårånd", family: "Aasen", id: "ata" },
];
